% Identification
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{UCFthesis}[2011/08/05 UCF Thesis or Dissertation]

% Preliminary declarations

% Options

% More declarations
\LoadClassWithOptions{report}

\RequirePackage{graphicx}
\RequirePackage{caption}

\RequirePackage[top=1.25in, bottom=1in, left=1in, right=1in]{geometry}

\RequirePackage{setspace}

\RequirePackage{sectsty}
\chapterfont{\centering \normalsize \uppercase}


\doublespacing

\renewcommand{\normalsize}{\fontsize{12}{12}\selectfont}

\pagestyle{plain}
